# prek.toml configuration file
minimum_prek_version = "0.4.0"

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.17"
hooks = [
    { id = "ruff-check", args = ["--fix"] },
    { id = "ruff-format" }
]
